--- 
Administrator:
  class: Administrator
  respond_to_private_messages: true
  command_prefix: ~
Pastr: 
  class: Pastr
  respond_to_private_messages: true
  command_prefix: .
LogBot:
  class: LogBot
  command_prefix: !
  log_channels: 
  - "#rubyists-Freenode"
  - "#rubyists-Efnet"
  - "#ramaze-Freenode"
  - "#lighttpd-Freenode"
