--- 
Efnet: 
  nick: Pastr
  leaves: 
  - Pastr
  - LogBot
  - Google
  - Arch
  - Administrator
  rejoin: true
  local_ip: 63.133.184.119
  server_id: Efnet
  channels: 
  - "#linuxgeneration"
  - "#linuxhelp"
  - "#regex"
  - "#debian"
  - "#philosophy"
  - "#ubuntu"
  - "#ruby"
  - "#rubyists": flipper
  server: irc.prison.net
Freenode: 
  nick: Pastr
  password: ZrDaGNTX
  leaves: 
  - Pastr
  - LogBot
  - Google
  - Arch
  - Administrator
  rejoin: true
  local_ip: 63.133.184.119
  server_id: Freenode
  channels: 
  - "#lighttpd"
  - "#pfsense"
  - "#rubyists"
  - "#rubyists-support"
  - "#rubyists.com": help
  - "#ramaze"
  - "#archlinux-offtopic"
  - "#rack"
  - "#sequel"
  - "#postgresql"
  - "#eventmachine"
  - "#mixxx"
  - "#ver"
  - "#ruby-de"
  - "#freeswitch-support": helpme
  server: irc.freenode.net
