--- 
Efnet: 
  nick: Pastr
  leaves: 
  - Pastr
  - LogBot
  - Administrator
  rejoin: true
  local_ip: 74.7.148.119
  server_id: Efnet
  channels: 
  - "#linuxgeneration"
  - "#philosophy"
  - "#linuxhelp"
  - "#regex"
  - "#debian"
  - "#philosophy"
  - "#ubuntu"
  - "#ruby"
  - "#rubyists": flipper
  server: irc.efnet.ru
Freenode: 
  nick: Pastr
  password: ZrDaGNTX
  leaves: 
  - Pastr
  - LogBot
  - Administrator
  rejoin: true
  local_ip: 74.7.148.119
  server_id: Freenode
  channels: 
  - "#queuetastic"
  - "#freeswitcher"
  - "#lighttpd"
  - "#emash"
  - "#autumn"
  - "#rubyists"
  - "#rubyists-support"
  - "#rubyists.com": help
  - "#ramaze"
  - "#rack"
  - "#sequel"
  - "#postgresql"
  - "#eventmachine"
  - "#mixxx"
  - "#freeswitch-support": helpme
  server: irc.freenode.net
