--- 
Efnet: 
  nick: Pastr
  leaves: 
  - Pastr
  - LogBot
  rejoin: true
  local_ip: 74.7.148.119
  server_id: Efnet
  channels: 
  - "#linuxgeneration"
  - "#philosophy"
  - "#linuxhelp"
  - "#regex"
  - "#debian"
  - "#ruby"
  - "#rubyists": flipper
  server: irc.easynews.com
Freenode: 
  nick: Pastr
  password: ZrDaGNTX
  leaves: 
  - Pastr
  - LogBot
  rejoin: true
  local_ip: 74.7.148.119
  server_id: Freenode
  channels: 
  - "#queuetastic"
  - "#freeswitcher"
  - "#lighttpd"
  - "#emash"
  - "#pastr"
  - "#rubyists"
  - "#ramaze"
  - "#sequel"
  - "#postgresql"
  - "#mixxx"
  - "#freeswitch-social"
  server: irc.freenode.net
