--- 
Efnet: 
  nick: PastrToo
  leaves: 
  - LogBot
  rejoin: true
  server_id: Efnet
  channels: 
  - "#rubyists": flipper
  server: irc.efnet.net
Freenode: 
  nick: PastrToo
  leaves: 
  - LogBot
  rejoin: true
  server_id: Freenode
  channel: "#rubyists"
  server: irc.freenode.net
